name: Notify about new data
on:
  push:
    branches:
      - main
      - test-dispatch
    paths:
      - "data/**"

jobs:
  ios:
    name: Tell iOS GitHub Actions to update data
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch workflow
        run: | # https://github.com/cesko-digital/movapp-apple/blob/main/.github/workflows/data-update.yml
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cesko-digital/movapp-apple/dispatches \
            -d '{"event_type":"data-update"}'
  android:
    name: Tell Android GitHub Actions to update data
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch workflow
        run: | # https://github.com/cesko-digital/movapp-android/blob/main/.github/workflows/data-update.yml
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cesko-digital/movapp-android/dispatches \
            -d '{"event_type":"data-update"}'
